import { ConfigProvider } from "antd";
import faIR from "antd/locale/fa_IR";
import "./styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import mainTheme from "@/assets/fonts/themes/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConfigProvider theme={mainTheme} locale={faIR} direction="rtl">
      <html dir="rtl" lang="fa" className="scroll-smooth">
        <body className={inter.className}>{children}</body>
      </html>
    </ConfigProvider>
  );
}
